# Generated by Django 2.0.2 on 2018-05-01 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mobile_sale_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.IntegerField(default=5)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 1, 0, 38, 942472))),
                ('content', models.CharField(blank=True, max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfileInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('phone_no', models.CharField(max_length=11)),
                ('birth_day', models.DateField(blank=True, default=datetime.date.today)),
                ('address', models.CharField(max_length=264)),
                ('social_id', models.CharField(max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True)),
                ('customer_name', models.CharField(max_length=264)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('customer_address', models.CharField(default='', max_length=264)),
                ('time_order', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 1, 0, 38, 942472), editable=False)),
                ('deliver_to', models.CharField(max_length=264)),
                ('note', models.CharField(blank=True, max_length=264)),
                ('kind_delivery', models.CharField(choices=[('F', 'Chuyển phát nhanh'), ('S', 'Chuyển hàng tiêu chuẩn')], default='S', max_length=1)),
                ('status', models.IntegerField(choices=[(1, 'Đã thanh toán'), (0, 'Đang xử lí'), (2, 'Đang vận chuyển')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('os', models.CharField(blank=True, choices=[('AND', 'Android'), ('IOS', 'Ios'), ('WDP', 'Window phone'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('name', models.CharField(max_length=264)),
                ('manufacturer', models.CharField(blank=True, choices=[('SAM', 'Samsung'), ('APP', 'Apple'), ('HTC', 'HTC'), ('NKA', 'Nokia'), ('BBR', 'Black Berry'), ('OPP', 'Oppo'), ('SN', 'Sony'), ('VV', 'Vivo'), ('HW', 'Huawei'), ('XM', 'Xiaomi'), ('AS', 'Asus'), ('MRL', 'Motorola'), ('OTH', 'Other')], default='OTH', max_length=264)),
                ('img', models.ImageField(blank=True, upload_to='product_pics')),
                ('price', models.IntegerField(default=0)),
                ('memory', models.FloatField()),
                ('camera_resolution', models.FloatField()),
                ('screen_size', models.FloatField()),
                ('weigth', models.FloatField()),
                ('color', models.CharField(max_length=10)),
                ('warranty', models.DateField()),
                ('price_sale', models.IntegerField(default=0)),
                ('battery', models.IntegerField()),
                ('sound', models.CharField(max_length=64)),
                ('product_code', models.CharField(default=mobile_sale_app.models.auto_increment_product_code, max_length=8)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('sale_rate', models.FloatField(blank=True, default=0)),
                ('item', models.CharField(blank=True, choices=[('', 'None'), ('USB', 'Usb'), ('PEN', 'Pen'), ('COU', 'Coupon'), ('KEY', 'Keychains')], default='', max_length=3)),
                ('type', models.BooleanField(choices=[(True, 'Discount'), (False, 'Bonus Item')], default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='mobile_sale_app.Sale'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=models.SET(''), to='mobile_sale_app.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_sale_app.CustomerProfileInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_sale_app.Product'),
        ),
    ]
