# Generated by Django 2.0.2 on 2018-05-01 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 1, 1, 28, 817260)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 1, 1, 28, 817260), editable=False),
        ),
    ]
