# Generated by Django 2.0.4 on 2018-05-21 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale_app', '0002_auto_20180502_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 17, 50, 1, 451707)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 17, 50, 1, 450705), editable=False),
        ),
    ]
